# Generated by Django 4.2.1 on 2023-10-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_order_remove_reservation_user_reservation_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
