# Generated by Django 4.2.7 on 2023-12-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_order_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.AlterField(
            model_name='order',
            name='postal',
            field=models.CharField(max_length=5),
        ),
    ]
